// Generated by CoffeeScript 1.6.3
(function() {
  var abridge, api, form, formElement, getUserName, insertRow, rform, showForm, submitForm, tid, weAddToResourceBank;

  form = [
    {
      name: 'topic',
      label: 'Topic:',
      type: 'text',
      req: true,
      err: 'Please indicate the focus of the resource.'
    }, {
      name: 'context',
      label: 'Context:',
      type: 'text',
      req: true,
      err: 'Please specify the context of the resource.'
    }, {
      name: 'url',
      label: 'URL:',
      type: 'text',
      req: true,
      err: 'Please provide the public URL to the resource.'
    }, {
      name: 'title',
      label: 'Title:',
      type: 'text',
      req: true,
      err: 'Please enter the title of the resource.'
    }, {
      name: 'pubdate',
      label: 'Publication Date:',
      type: 'text',
      req: true,
      err: 'Please enter the first publication year of the resource.'
    }, {
      name: 'comment',
      label: 'Comment:',
      type: 'textarea',
      req: true,
      err: 'Please provide a brief comment about the resource.'
    }
  ];

  rform = {};

  tid = '';

  api = function(data, success, failure) {
    data.action || (data.action = 'query');
    data.format || (data.format = 'json');
    return $.ajax({
      url: window.wgServer + '/api.php',
      type: 'POST',
      data: data,
      success: success,
      failure: failure
    });
  };

  formElement = function(x) {
    var disabled, ni, o, r, selected, t, text, v, _i, _len, _ref, _ref1, _ref2;
    r = "<td class=\"mw-label\"><label for=\"WErb" + x.name + "\">" + x.label + "</label></td>";
    ni = "name=\"WErb" + x.name + "\" id=\"WErb" + x.name + "\"";
    switch (x.type) {
      case "select":
        r += '<td class="mw-input"><select ' + ni + '>';
        _ref = x.options;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          o = _ref[_i];
          if (typeof o === 'string') {
            _ref1 = [o, o, o, false, false], v = _ref1[0], t = _ref1[1], text = _ref1[2], selected = _ref1[3], disabled = _ref1[4];
          } else {
            _ref2 = [o.value, o.title, o.text, o.selected, o.disabled], v = _ref2[0], t = _ref2[1], text = _ref2[2], selected = _ref2[3], disabled = _ref2[4];
          }
          r += "<option value=\"" + v + "\" title=\"" + t + "\"";
          if (disabled) {
            r += ' disabled="disabled"';
          }
          if (selected) {
            r += ' selected';
          }
          r += ">" + text + "</option>";
        }
        return r += "</select>            <div style=\"font-size: smaller;\">" + (x.note || '&nbsp;') + "</div></td>";
      case "textarea":
        return r += "<td class=\"mw-input\"><textarea " + ni + " rows=2 cols=40></textarea><div style=\"font-size:smaller;\">" + (x.note || '&nbsp;') + "</div></td>";
      default:
        r += "<td class=\"mw-input\"><input " + ni + " type=\"text\" size=\"40\"";
        if (x.disabled) {
          r += ' disabled="disabled"';
        }
        return r += " /><div style=\"font-size: smaller;\">" + (x.note || '&nbsp;') + "</div></td>";
    }
  };

  abridge = function(text) {
    var maxlen, p;
    maxlen = 150;
    if (text.length > maxlen) {
      p = maxlen;
      while (p > 1 && text.charAt(p) !== ' ') {
        p--;
      }
      text = text.slice(0, p - 1);
    }
    return text;
  };

  insertRow = function(text, row) {
    var end, p, start;
    p = text.indexOf('|-', text.indexOf('id="#{tid}"'));
    if (p > 0) {
      start = text.slice(0, p - 1);
      end = text.slice(p);
      return start + row + end;
    }
    return '';
  };

  submitForm = function() {
    var $es, element, err, row, v, _i, _len;
    err = false;
    for (_i = 0, _len = form.length; _i < _len; _i++) {
      element = form[_i];
      $es = $("#WErb" + element.name);
      v = $.trim($es.val());
      if (element.req && v === "") {
        $es.next().text(element.err).css('color', 'FireBrick');
        err = true;
      } else {
        $es.next().html('&nbsp;');
        rform[element.name] = v;
      }
    }
    if (err) {
      return false;
    }
    $('#weAddToResourceBankSubmit').hide();
    $('#WErbSpinner').show();
    api({
      prop: 'info|revisions',
      intoken: 'edit',
      rvprop: 'content',
      titles: window.wgPageName
    }, function(d) {
      var comment, p, pages, text, token, _ref, _results;
      pages = d != null ? (_ref = d.query) != null ? _ref.pages : void 0 : void 0;
      _results = [];
      for (p in pages) {
        token = pages[p].edittoken;
        text = pages[p].revisions[0]['*'];
        api({
          action: 'edit',
          title: window.wgPageName,
          summary: "Add " + rform.context + " resource",
          text: insertRow(text, row),
          token: token,
          unwatch: 1
        }, function(d) {
          return window.location = "" + window.wgServer + "/" + window.wgPageName + "?1";
        }, function() {
          alert("Unable to save resource.  Please try later.");
          return window.location = "" + window.wgServer + "/" + window.wgPageName + "?1";
        });
        comment = abridge(rform.comment);
        api({
          action: 'wenotes',
          notag: 'oeruesp',
          notext: "New " + rform.context + " (" + rform.topic + ") resource: " + rform.title + " " + rform.url + " " + comment
        }, function() {
          var t;
          return t = 1;
        }, function() {
          var t;
          return t = 2;
        });
        break;
      }
      return _results;
    }, function() {
      var pass;
      return pass = 1;
    });
    row = [];
    row.push("\n|-");
    row.push('   0<br />&#x2606;');
    row.push(rform.topic);
    row.push(rform.context);
    row.push("[" + rform.url + " " + rform.title + "]. " + rform.pubdate + ".");
    row.push(rform.comment);
    row.push("[[User:" + rform.user + "|" + rform.user_name + "]]\n");
    row = row.join("\n|");
    return false;
  };

  showForm = function() {
    /*
    if window.wgUserName is null
      alert("You must be logged in to WikiEducator to add an entry")
      return false
    */

    $('#weAddToResourceBankDialog').dialog({
      height: 500,
      width: 680,
      title: 'Add to Resource Bank',
      show: 'slow'
    });
    getUserName();
    return false;
  };

  getUserName = function() {
    rform.user = window.wgUserName;
    return api({
      meta: 'userinfo',
      uiprop: 'realname'
    }, function(d) {
      var userinfo, _ref;
      if ((_ref = d.query) != null ? _ref.userinfo : void 0) {
        userinfo = d.query.userinfo;
        return rform.user_name = userinfo.realname;
      }
    });
  };

  weAddToResourceBank = function(id, login, button) {
    var $did, element, _fn, _i, _len;
    $did = $("#b" + id);
    if (window.wgUserName) {
      $did.append("<button></button>");
      $did.find('button').text(button);
    } else {
      $did.html('<a href="http://wikieducator.org/index.php?title=Special:UserLogin&returnto=#{window.wgPageName}"></a>');
      $did.find('a').text(login);
      return false;
    }
    tid = id;
    $('body').append("<div id=\"weAddToResourceBankDialog\" style=\"display:none;\">\n  <form id=\"fweAddToResourceBank" + id + "\">\n    <table></table>\n  </form>\n</div>");
    _fn = function(element) {
      return $("#weAddToResourceBankDialog > form > table").append('<tr>' + formElement(element) + "</tr>\n");
    };
    for (_i = 0, _len = form.length; _i < _len; _i++) {
      element = form[_i];
      _fn(element);
    }
    $('#weAddToResourceBankDialog > form > table').append('<tr><td>&nbsp;</td>\n  <td><img id="WErbSpinner" src="/skins/common/images/Ajax-loader.gif"\n        height=16 width=16 style="display: none" /><button\n        id="weAddToResourceBankSubmit">Submit</button></td></tr>');
    $did.find('button').click(showForm);
    $('#weAddToResourceBankSubmit').click(submitForm);
    return false;
  };

  jQuery(function() {
    window.weAddToResourceBank = weAddToResourceBank;
  });

}).call(this);
